version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:20.04
   steps:
      - run:
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install axel bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev rsync flex bison binutils
           git config --global user.name "Sohil876"
           git config --global user.email "sohil876@gmail.com"
           git config --global color.ui false
           git clone https://github.com/akhilnarang/scripts && cd scripts && bash setup/android_build_env.sh && cd ..
           mkdir nbm69
           cd nbm69
           wget https://raw.githubusercontent.com/Sohil876/android_kernel_xiaomi_tissot/11.0/.circleci/build.sh
           bash build.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
